CREATE TABLE IF NOT EXISTS todoList (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS todo (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  status INTEGER DEFAULT 0,
  todoListId INTEGER,
  FOREIGN KEY (todoListId) REFERENCES todoList(id)
);
